"""
Meridian local brain skeleton.

Proactive portfolio orchestrator core — domain objects, decision engine,
events, and session injection modeling. No real model calls or UI yet.
"""

from .models import (
    Portfolio,
    Venture,
    Project,
    Initiative,
    Objective,
    Task,
    NextMove,
    Harness,
    Heartbeat,
    Workflow,
    Decision,
    ScottBottleneck,
    Proof,
    Artifact,
    SessionInjection,
    ProviderAdapter,
    HeartbeatStatus,
    InjectionMode,
    AdapterTier,
    Priority,
    MoveKind,
)
from .decisions import run_decision_loop, DecisionResult
from .events import EventRecorder, Event, EventKind
from .injections import make_injection
from .intention import (
    ObjectiveStage,
    MissionObjectiveLine,
    ProgressIntention,
    build_progress_intention,
)
from .mission import (
    load_mission,
    find_mission_file,
    Mission,
    MissionLoadError,
)
from .wake import build_wake_brief, WakeBrief, WakeLine, WakeStatus
from .objectives import get_mission_objectives, format_mission_objectives_text
from .risk import RiskTier, RiskMode, RiskAssessment, assess_tier, assess_blocked_action
from .relay import (
    RoutingMode,
    ModelRole,
    ContextStrategy,
    CostPosture,
    VendorRouteKind,
    AccessRouteClass,
    SessionAction,
    RouteTrustState,
    RelayLane,
    RelayRouteAudit,
    RelayRoute,
    route_from_tier,
    route_from_assessment,
)
from .aegis import (
    EvidenceType,
    EvidenceStatus,
    EvidenceSeverity,
    AegisEvidence,
    ProofTrail,
    evidence_from_cross_check,
)
from .cross_check import (
    CrossCheckDisposition,
    CrossCheckDispositionAction,
    CrossCheckFinding,
    CrossCheckFindingStatus,
    CrossCheckRepairRoute,
    CrossCheckRunRequest,
    CrossCheckRunResult,
    CrossCheckRunStatus,
    CrossCheckSeverity,
    CrossCheckValidationError,
    CrossCheckVerificationRequest,
    CrossCheckVerificationResult,
    dispose_finding,
    execute_cross_check,
    rerun_verification,
    route_finding_for_repair,
)
from .review_console import (
    ReviewConsoleItemType,
    ReviewConsoleSeverity,
    ReviewConsoleAction,
    ReviewConsoleItemStatus,
    ReviewConsoleItem,
    ReviewConsoleResponse,
    ReviewConsoleQueue,
    make_cross_check_item,
    make_plan_review_item,
    make_approval_gate,
    make_system_finding,
    make_prompt_metrics_finding,
)
from .builds import (
    HarnessMaturity,
    HarnessBuild,
    MeridianBuild,
    BuildRegistry,
    make_initial_registry,
)
from .filemap import FileMapEntry, FileMap, FileArea, make_default_map
from .council import (
    CouncilRole,
    CouncilPosition,
    CouncilPlan,
    default_council_positions,
    council_plan_for_tier,
)
from .prompt_budget import (
    PromptBudgetTier,
    PromptBudget,
    PromptBudgetPlan,
    prompt_budget_for_risk_tier,
)
from .prompt_metrics import (
    PromptMetricSample,
    PromptMetricSummary,
    PromptPerformanceStatus,
    summarize_prompt_metrics,
)
from .prompt_packet import (
    PromptPacket,
    PromptPacketValidationError,
    build_prompt_packet,
)
from .beacon import LivenessTarget, check_harness_liveness
from .planning import (
    PlanningAnswer,
    PlanningQuestion,
    PlanningRecommendation,
    PlanningBrief,
    PlanningContext,
    build_planning_brief,
)
from .session_lifecycle import (
    CloseArchiveWriteThroughAction,
    ObsidianCaptureResult,
    SessionCloseWriteThroughRequest,
    SessionCloseWriteThroughResult,
    SessionWriteThroughResult,
    close_session_with_write_through,
)
from .backlog import (
    BacklogBlockedStatus,
    BacklogImportCandidate,
    BacklogImportBatch,
    BacklogItem,
    BacklogItemState,
    BacklogOwner,
    BacklogPriority,
    BacklogQuery,
    BacklogScope,
    BacklogSource,
    BacklogTaskDraft,
    BacklogValidationError,
    approve_backlog_item,
    archive_backlog_item,
    capture_backlog_item,
    convert_backlog_item_to_task_draft,
    defer_backlog_item,
    deny_backlog_item,
    import_backlog_candidates,
    link_backlog_item_scope,
    load_backlog,
    modify_backlog_item,
    query_backlog,
    reject_backlog_item,
    save_backlog,
    to_goal_objective_ref,
)
from .voice_io import (
    VoiceCommandIntent,
    VoiceIntentFamily,
    VoiceMode,
    VoiceOutputJob,
    VoiceOutputStatus,
    VoicePrivacyLevel,
    VoiceProviderCapability,
    VoiceRuntimeState,
    VoiceTranscriptDraft,
    VoiceTrustState,
    VoiceValidationError,
    apply_transcript_correction,
    build_voice_runtime_state,
    create_output_job,
    create_transcript_draft,
    interrupt_output_job,
    mute_output_job,
    normalize_voice_intent,
)

from .cockpit_state import (
    CockpitStatus,
    QueuePolicy,
    ProgressEventCategory,
    EventSeverity,
    LaneCockpitStatus,
    LaneSummary,
    ProgressEvent,
    PrimeCockpitSnapshot,
    sort_lanes,
    filter_events,
    lane_summary_counts,
)
from .cockpit_provider import (
    build_snapshot,
    demo_snapshot,
)
from .cognition_policy import (
    CognitionActionType,
    CognitionLane,
    CognitionDecision,
    CognitionPolicy,
    CognitionPolicyResult,
    cognition_policy_for_tier,
    evaluate_cognition_policy,
)

__all__ = [
    # -- Core domain models --------------------------------------------------
    "Portfolio",
    "Venture",
    "Project",
    "Initiative",
    "Objective",
    "Task",
    "NextMove",
    "Harness",
    "Heartbeat",
    "Workflow",
    "Decision",
    "ScottBottleneck",
    "Proof",
    "Artifact",
    "SessionInjection",
    "ProviderAdapter",
    "HeartbeatStatus",
    "InjectionMode",
    "AdapterTier",
    "Priority",
    "MoveKind",
    # -- Decision loop --------------------------------------------------------
    "run_decision_loop",
    "DecisionResult",
    # -- Events and injections ------------------------------------------------
    "EventRecorder",
    "Event",
    "EventKind",
    "make_injection",
    # -- Progress intention / Compass -----------------------------------------
    "ObjectiveStage",
    "MissionObjectiveLine",
    "ProgressIntention",
    "build_progress_intention",
    # -- Mission boot ---------------------------------------------------------
    "load_mission",
    "find_mission_file",
    "Mission",
    "MissionLoadError",
    # -- Wake sequence --------------------------------------------------------
    "build_wake_brief",
    "WakeBrief",
    "WakeLine",
    "WakeStatus",
    # -- Mission objectives ---------------------------------------------------
    "get_mission_objectives",
    "format_mission_objectives_text",
    # -- Risk tier engine -----------------------------------------------------
    "RiskTier",
    "RiskMode",
    "RiskAssessment",
    "assess_tier",
    "assess_blocked_action",
    # -- Relay routing --------------------------------------------------------
    "RoutingMode",
    "ModelRole",
    "ContextStrategy",
    "CostPosture",
    "VendorRouteKind",
    "AccessRouteClass",
    "SessionAction",
    "RouteTrustState",
    "RelayLane",
    "RelayRouteAudit",
    "RelayRoute",
    "route_from_tier",
    "route_from_assessment",
    # -- Aegis / proof harness ------------------------------------------------
    "EvidenceType",
    "EvidenceStatus",
    "EvidenceSeverity",
    "AegisEvidence",
    "ProofTrail",
    "evidence_from_cross_check",
    # -- Cross-check authority ----------------------------------------------
    "CrossCheckDisposition",
    "CrossCheckDispositionAction",
    "CrossCheckFinding",
    "CrossCheckFindingStatus",
    "CrossCheckRepairRoute",
    "CrossCheckRunRequest",
    "CrossCheckRunResult",
    "CrossCheckRunStatus",
    "CrossCheckSeverity",
    "CrossCheckValidationError",
    "CrossCheckVerificationRequest",
    "CrossCheckVerificationResult",
    "dispose_finding",
    "execute_cross_check",
    "rerun_verification",
    "route_finding_for_repair",
    # -- Review Console -------------------------------------------------------
    "ReviewConsoleItemType",
    "ReviewConsoleSeverity",
    "ReviewConsoleAction",
    "ReviewConsoleItemStatus",
    "ReviewConsoleItem",
    "ReviewConsoleResponse",
    "ReviewConsoleQueue",
    "make_cross_check_item",
    "make_plan_review_item",
    "make_approval_gate",
    "make_system_finding",
    "make_prompt_metrics_finding",
    # -- Build and maturity registry ------------------------------------------
    "HarnessMaturity",
    "HarnessBuild",
    "MeridianBuild",
    "BuildRegistry",
    "make_initial_registry",
    # -- File map knowledge tracker -------------------------------------------
    "FileMapEntry",
    "FileMap",
    "FileArea",
    "make_default_map",
    # -- Council cognition ----------------------------------------------------
    "CouncilRole",
    "CouncilPosition",
    "CouncilPlan",
    "default_council_positions",
    "council_plan_for_tier",
    # -- Relay prompt budget --------------------------------------------------
    "PromptBudgetTier",
    "PromptBudget",
    "PromptBudgetPlan",
    "prompt_budget_for_risk_tier",
    # -- Relay prompt metrics -------------------------------------------------
    "PromptMetricSample",
    "PromptMetricSummary",
    "PromptPerformanceStatus",
    "summarize_prompt_metrics",
    # -- Prompt packet --------------------------------------------------------
    "PromptPacket",
    "PromptPacketValidationError",
    "build_prompt_packet",
    # -- Beacon liveness -----------------------------------------------------
    "LivenessTarget",
    "check_harness_liveness",
    # -- Planning harness ----------------------------------------------------
    "PlanningAnswer",
    "PlanningQuestion",
    "PlanningRecommendation",
    "PlanningBrief",
    "PlanningContext",
    "build_planning_brief",
    # -- Session Lifecycle SK9 close/write-through authority -----------------
    "CloseArchiveWriteThroughAction",
    "ObsidianCaptureResult",
    "SessionCloseWriteThroughRequest",
    "SessionCloseWriteThroughResult",
    "SessionWriteThroughResult",
    "close_session_with_write_through",
    # -- Backlog Authority ---------------------------------------------------
    "BacklogBlockedStatus",
    "BacklogImportCandidate",
    "BacklogImportBatch",
    "BacklogItem",
    "BacklogItemState",
    "BacklogOwner",
    "BacklogPriority",
    "BacklogQuery",
    "BacklogScope",
    "BacklogSource",
    "BacklogTaskDraft",
    "BacklogValidationError",
    "approve_backlog_item",
    "archive_backlog_item",
    "capture_backlog_item",
    "convert_backlog_item_to_task_draft",
    "defer_backlog_item",
    "deny_backlog_item",
    "import_backlog_candidates",
    "link_backlog_item_scope",
    "load_backlog",
    "modify_backlog_item",
    "query_backlog",
    "reject_backlog_item",
    "save_backlog",
    "to_goal_objective_ref",
    # -- Voice I/O Authority ------------------------------------------------
    "VoiceCommandIntent",
    "VoiceIntentFamily",
    "VoiceMode",
    "VoiceOutputJob",
    "VoiceOutputStatus",
    "VoicePrivacyLevel",
    "VoiceProviderCapability",
    "VoiceRuntimeState",
    "VoiceTranscriptDraft",
    "VoiceTrustState",
    "VoiceValidationError",
    "apply_transcript_correction",
    "build_voice_runtime_state",
    "create_output_job",
    "create_transcript_draft",
    "interrupt_output_job",
    "mute_output_job",
    "normalize_voice_intent",
    # -- Cockpit state --------------------------------------------------------
    "CockpitStatus",
    "QueuePolicy",
    "ProgressEventCategory",
    "EventSeverity",
    "LaneCockpitStatus",
    "LaneSummary",
    "ProgressEvent",
    "PrimeCockpitSnapshot",
    "sort_lanes",
    "filter_events",
    "lane_summary_counts",
    # -- Cockpit provider ----------------------------------------------------
    "build_snapshot",
    "demo_snapshot",
    # -- V2 Cognition policy --------------------------------------------------
    "CognitionActionType",
    "CognitionLane",
    "CognitionDecision",
    "CognitionPolicy",
    "CognitionPolicyResult",
    "cognition_policy_for_tier",
    "evaluate_cognition_policy",
]
